import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import Provider from "@/lib/jotaiprovider";
import verify from "@/utils/verify";

export const metadata: Metadata = {
  title: "Chatio",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { auth, username } = await verify();
  return (
    <html lang="en">
      <Provider>
        <body className="pt-4">
          <Navbar auth={auth} username={username} />
          <div className="pt-5">{children}</div>
        </body>
      </Provider>
    </html>
  );
}
